version: "3.9"

services:
  admin-panel:
    container_name: microfinance-admin-panel

    build:
      context: .
      dockerfile: Dockerfile

    image: microfinance-admin-panel:latest

    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    networks:
      - microfinance-network

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  microfinance-network:
    external: true